#!/bin/sh
# Set the wallpaper to the most recent XKCD comic
# requires imagemagick and jq
RESOLUTION=1366x768
OUT_DIR=~/xkcd

setWallpaper () {
	display -backdrop -background '#ffffff' -flatten -window root $OUT_DIR/current.png
}
setWallpaper

# Wait for a connection
for i in {1..50}; do ping -c1 xkcd.com && break; done

CURRENT_COMIC_URL=`curl https://xkcd.com/info.0.json | jq -r .img`
OUT_FILE=$OUT_DIR/`date +"%Y%m%d"`.png
echo $OUT_FILE
curl $CURRENT_COMIC_URL -o $OUT_FILE

# Make a wallpaper version
convert $OUT_FILE \
-gravity center \
-background white \
-extent $RESOLUTION \
$OUT_DIR/current.png

# Make a dark version
convert $OUT_DIR/current.png \
-channel RGB -negate \
$OUT_DIR/current-dark.png

setWallpaper
